name: process_run
version: 0.5.2
description: Process run helpers for Linux/Win/Mac
homepage: https://github.com/tekartik/process_run.dart
author: Tekartik <dev@tekartik.com>
environment:
  sdk: '>=1.24.2 <2.0.0'
dependencies:
  path: '>=1.3.9'
  collection: '>=1.9.1'
dev_dependencies:
  pub_semver: any
  args: any
  dev_test: any
  test: any
  async: any

executables:
  cmd_record: