name: process_run
version: 0.8.0+1
description: Process run helpers for Linux/Win/Mac
homepage: https://github.com/tekartik/process_run.dart
author: Tekartik <dev@tekartik.com>

environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'

dependencies:
  path: '>=1.6.1 <3.0.0'
  collection: '>=1.14.10 <3.0.0'

dev_dependencies:
  pub_semver: any
  args: any
  dev_test: any
  test: '>=1.2.0'
  async: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
