name: process_run
version: 0.12.0-nullsafety.0
description: Process run helpers for Linux/Win/Mac and which like feature for finding executables.
homepage: https://github.com/tekartik/process_run.dart

environment:
  sdk: '>=2.10.0-29 <3.0.0'

dependencies:
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  collection: '>=1.15.0-nullsafety.5 <3.0.0'
  io: '>=0.3.0 <2.0.0'
  # yaml: '>=2.0.0 <4.0.0'
  yaml: '>=3.0.0-nullsafety.0'
  meta: '>=1.3.0-nullsafety.6 <3.0.0'
  args: '>=1.5.0 <3.0.0'
  pub_semver: '>=1.4.0 <3.0.0'
  synchronized: '>=3.0.0-nullsafety.1 <4.0.0'

dev_dependencies:
  pedantic: '>=1.4.0'
  # test: '>=1.2.0'
  test: '>=1.16.0-nullsafety.11'
  async: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'

executables:
  # Shell helper
  ds: shell

# temp nnbd
dependency_overrides:
  yaml: '>=3.0.0-nullsafety.0'
  analyzer: '>=0.41.1'