name: process_run
version: 0.4.0
description: Process run helpers for Linux/Win/Mac
homepage: https://github.com/tekartik/process_run.dart
author: Tekartik <dev@tekartik.com>
environment:
  sdk: '>=1.19.1 <2.0.0'
dependencies:
  path: '>=1.3.9'
  collection: '>=1.9.1'
dev_dependencies:
  pub_semver: any
  args: any
  dev_test: any
  test: any
